# Generated by Django 6.0.6 on 2026-06-22 08:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_fat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_fat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_fat'],
            },
        ),
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('snf_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('rate_per_liter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_entries', to='farmers.farmer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('farmer', 'date', 'shift')},
            },
        ),
    ]
